-- MS SQL 2012

CREATE DATABASE [ExplorerBeyond]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ExplorerBeyond', FILENAME = N'......\ExplorerBeyond\db\ExplorerBeyond.mdf' , SIZE = 5120KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ExplorerBeyond_log', FILENAME = N'......\ExplorerBeyond\db\ExplorerBeyond_log.ldf' , SIZE = 2048KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [ExplorerBeyond] SET COMPATIBILITY_LEVEL = 110
GO
ALTER DATABASE [ExplorerBeyond] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ExplorerBeyond] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ExplorerBeyond] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ExplorerBeyond] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ExplorerBeyond] SET ARITHABORT OFF 
GO
ALTER DATABASE [ExplorerBeyond] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ExplorerBeyond] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [ExplorerBeyond] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ExplorerBeyond] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ExplorerBeyond] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ExplorerBeyond] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ExplorerBeyond] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ExplorerBeyond] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ExplorerBeyond] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ExplorerBeyond] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ExplorerBeyond] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ExplorerBeyond] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ExplorerBeyond] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ExplorerBeyond] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ExplorerBeyond] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ExplorerBeyond] SET  READ_WRITE 
GO
ALTER DATABASE [ExplorerBeyond] SET RECOVERY FULL 
GO
ALTER DATABASE [ExplorerBeyond] SET  MULTI_USER 
GO
ALTER DATABASE [ExplorerBeyond] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ExplorerBeyond] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
USE [ExplorerBeyond]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [ExplorerBeyond] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
